export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const COMPARE_PRODUCT = 'COMPARE_PRODUCT';
export const FILTER_PRODUCT_BY_COLOR = 'FILTER_PRODUCT_BY_COLOR';
export const FILTER_PRODUCT_BY_PRICE = 'FILTER_PRODUCT_BY_PRICE';
